# Generated by Django 4.2.2 on 2024-05-22 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='user_field_usernameHelpTxt', max_length=30, unique=True, verbose_name='user_field_username')),
                ('password', models.CharField(max_length=128, verbose_name='user_field_password')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='user_field_firstName')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='user_field_lastName')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='user_field_email')),
                ('login_id', models.IntegerField(blank=True, default=0, null=True)),
                ('login_type', models.IntegerField(blank=True, default=0, null=True)),
                ('is_student', models.BooleanField(default=False, help_text='user_field_staffStatusHelpTxt', verbose_name='user_field_staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='user_field_dateJoined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='user_field_lastLogin')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('college_name', models.CharField(blank=True, max_length=36, null=True, verbose_name='user_field_current_company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='myuser_set', related_query_name='myuser', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='myuser_set', related_query_name='myuser', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
